-- Create airlab_readings table for air quality sensor data
CREATE TABLE IF NOT EXISTS public.airlab_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    co2_ppm DOUBLE PRECISION,
    temperature_c DOUBLE PRECISION,
    humidity_percent DOUBLE PRECISION,
    pressure_hpa DOUBLE PRECISION,
    voc_index DOUBLE PRECISION,
    nox_index DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_airlab_timestamp ON public.airlab_readings (timestamp);

COMMENT ON TABLE public.airlab_readings IS 'Air quality sensor readings from airlab';
COMMENT ON COLUMN public.airlab_readings.co2_ppm IS 'CO2 concentration in parts per million';
COMMENT ON COLUMN public.airlab_readings.temperature_c IS 'Temperature in degrees Celsius';
COMMENT ON COLUMN public.airlab_readings.humidity_percent IS 'Relative humidity percentage';
COMMENT ON COLUMN public.airlab_readings.pressure_hpa IS 'Atmospheric pressure in hectopascals';
COMMENT ON COLUMN public.airlab_readings.voc_index IS 'Volatile organic compounds index';
COMMENT ON COLUMN public.airlab_readings.nox_index IS 'Nitrogen oxides index';
